### ISSUE TITLE
Replacement of JavaFX WebView

### ISSUE THREAD

**Issue by anidotnet** [miho/VFXWebKit#1]
I came here from [this mailing list](http://mail.openjdk.java.net/pipermail/openjfx-dev/2016-June/019295.html). I was wondering how much complete is it? Can it be used as a replacement of standard WebView control?

**Comment by miho** [comment]
Honestly, it is still a long way to go. Here's a JDK issue that I submitted a while ago which would help a lot:

https://bugs.openjdk.java.net/browse/JDK-8167148
